# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: butterflys.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='butterflys.proto',
  package='butterfly',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x62utterflys.proto\x12\tbutterfly\"%\n\tButterfly\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t')
)




_BUTTERFLY = _descriptor.Descriptor(
  name='Butterfly',
  full_name='butterfly.Butterfly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='butterfly.Butterfly.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='butterfly.Butterfly.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Butterfly'] = _BUTTERFLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Butterfly = _reflection.GeneratedProtocolMessageType('Butterfly', (_message.Message,), dict(
  DESCRIPTOR = _BUTTERFLY,
  __module__ = 'butterflys_pb2'
  # @@protoc_insertion_point(class_scope:butterfly.Butterfly)
  ))
_sym_db.RegisterMessage(Butterfly)


# @@protoc_insertion_point(module_scope)
